// ##### Test Display ##### //

import React from 'react'

class Test extends React.Component {
  render() {
		return (
			<div className="c-grid">
	   		<header><b>Header</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur sunt voluptatem dolorum pariatur molestias iusto mollitia dignissimos esse, quisquam magni ex libero aperiam numquam eaque cum natus ducimus earum obcaecati qui vel provident laboriosam dicta ipsum quaerat! Quo praesentium corporis, ratione voluptates reprehenderit earum accusamus aperiam! Deleniti labore consectetur, perferendis, numquam libero repellat debitis rem delectus reprehenderit qui ab ex, voluptatibus obcaecati odit cupiditate at quam dolores eaque ipsam exercitationem sint reiciendis hic veniam pariatur in. Ab quasi sed minima, neque quia iure. Nesciunt ea voluptates placeat, deleniti culpa accusamus. Natus, unde reprehenderit nemo assumenda dolor, eos optio inventore quas?</header>
        <main><b>Main Content</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur dolore iure eaque laudantium temporibus sed repudiandae nemo, quia assumenda illum omnis impedit modi, sint accusamus doloremque rem necessitatibus amet neque quo cupiditate nesciunt error dignissimos quidem ex? Id vero ducimus harum beatae aut dolorem, fugit, quas reprehenderit non tenetur ab minus aliquam, aperiam magni, est cumque. Ab provident iste dolor, necessitatibus magnam amet porro iusto! Libero eveniet sed nostrum inventore ex dolore, culpa quisquam aliquam natus officiis dolorum dolorem doloremque beatae, sunt nemo recusandae enim quos tempore. Voluptatum quam numquam eligendi deserunt dolor consequuntur pariatur, sint maiores dicta voluptatibus incidunt rerum quis ea labore, harum impedit consectetur iure veritatis, magni odit explicabo praesentium fugiat omnis. Earum excepturi enim dolores iusto odio pariatur soluta. Iusto sed odio repellat ipsa consequuntur nihil nobis a molestias aut fugiat. Quisquam accusantium nisi eum, vero saepe ad assumenda accusamus voluptates omnis ipsa non sed aut, fugit, quo, impedit laboriosam placeat provident atque? Obcaecati dolor repellat debitis laudantium eaque officia, sapiente, delectus distinctio facilis incidunt dolores similique iusto expedita exercitationem? Illo repellendus optio quidem quo officia incidunt sint quam, doloremque pariatur, facere debitis, distinctio sed corporis. Deserunt, odit, facere facilis molestias impedit adipisci ducimus nostrum doloribus!</main>
        <aside><b>Left Column</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet ipsa, a quo at dicta expedita delectus natus itaque nam iste excepturi eius in illo facere omnis aliquam alias consequatur quae porro nihil? Eius vel laborum ut enim quae voluptatibus, beatae illum quo dolor animi ex sit, delectus aut est fugit praesentium! Nobis sequi quae eius unde quasi, nam maiores vitae tenetur voluptas eveniet quos optio placeat quidem necessitatibus deleniti aperiam. Odit quae accusamus quasi aliquid expedita ratione neque velit facere molestias. Dolor fugit voluptatum aliquam non consequuntur ullam praesentium qui animi distinctio in, ducimus totam quo laudantium possimus ab nisi.</aside>
        <aside><b>Right Column</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi fugit eveniet quibusdam minus esse eligendi tenetur qui, pariatur doloribus fugiat quisquam debitis aliquam, natus, quam quas maxime ab amet. Velit praesentium aperiam a aspernatur distinctio natus tempore, quas alias eos repellendus ipsa et facere pariatur harum rem quis beatae eum culpa. Tenetur praesentium aliquid eius eaque tempora, fuga totam obcaecati labore exercitationem ea veniam dignissimos cum maiores, optio saepe, accusantium porro minima nobis, voluptatem officiis consectetur? Quod, tenetur tempora magnam placeat alias eos voluptatibus praesentium porro sed consectetur ut omnis voluptatem doloremque nisi unde rem! Eum officiis debitis voluptate sapiente!</aside>
        <footer><b>Footer</b> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse earum ab nostrum optio at officiis placeat aliquam facere ipsum id ratione vero, eum necessitatibus ad dolorem numquam repellat totam corrupti. Voluptatum molestias praesentium modi nostrum vel delectus hic dolor, pariatur cum velit atque, quidem nobis inventore, ea vitae dolores cumque. Mollitia quo fuga, incidunt consequuntur quos eius eaque recusandae, minima expedita repellat quas excepturi cupiditate. Nulla, sit repellendus rerum voluptatum commodi porro fuga suscipit similique sunt labore quo culpa esse assumenda, voluptas cumque dolorem corporis quasi ratione, atque, molestias libero illo et dicta omnis. Velit, architecto ipsa similique dicta veritatis?</footer>
	    </div>
  	)
	}
}

module.exports = Test;
